server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: tiffin-service-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL:jdbc:h2:file:./data/tiffindb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE}}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  cache:
    type: simple # defaults to in-memory Spring Cache, seamlessly upgradable to redis
    cache-names:
      - menus
      - prices
      - dashboardStats
      - userBalances

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

tiffin:
  app:
    jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    jwtExpirationMs: 86400000 # 24 hours
    currencySymbol: "Rs."
    defaultFullPrice: 120.00
    defaultHalfPrice: 80.00

logging:
  level:
    root: INFO
    com.tiffin.system: DEBUG
